### ISSUE TITLE
B8 used for Hyperspectral ResNet but not downloaded in Preprocessing

### ISSUE THREAD

**Issue by aamir-s18** [chrisyeh96/africa_poverty_clean#3]
Hey,

I am currently doing a project based on your work. I am reimplementing the Hyperspectral ResNet in Pytorch and realized it uses the Panchromatic Band (B8), but it's not downloaded in the preprocessing. Also, why the RGB has a resolution of 15m? Are you using pan-sharpened images or something like this? 

It would be great if you could answer it! :)

**Comment by chrisyeh96** [comment]
I'm not sure I fully understand your question. My code does not use the Panchromatic Band (B8), so it does not download the panchromatic band. However, I am aware that some users of Landsat imagery use the panchromatic band to perform "pan-sharpening" of the RGB bands, which effectively upsamples them from 30m/px to 15m/px.

I am not sure what Hyperspectral ResNet PyTorch implementation you are referring to.

**Comment by aamir-s18** [comment]
Thank you for your quick reply, and sorry for not being clear. I am referring to the Panchromatic Band (B8) [here](https://github.com/chrisyeh96/africa_poverty_clean/blob/main/models/hyperspectral_resnet.py#L297) in the comments. I wanted to reimplement this part in Pytorch on my own. I wondered about the comments and the code since you didn't download the Panchromatic Band, but it seems like that model is using it? Maybe I am missing something.

**Comment by chrisyeh96** [comment]
Oh, the code that you linked to is for dilated convolutions. We didn't end up using dilated convolutions for the models in out 2020 Nature Communications paper. However, we did use dilated convolutions for an earlier version of this project, https://arxiv.org/abs/1711.03654, which also used the panchromatic band for pan-sharpening the RGB images to 15m/px.

If you are trying to reproduce the results from the 2020 Nature Communications paper, you can feel free to ignore the Panchromatic Band (B8) and also ignore the code for dilated convolutions.
